package com.assistant.ai.deepanalysis.models

import kotlinx.serialization.Serializable

/**
 * Diagram generated by AI during deep analysis.
 * Supports dual format: Mermaid (default) and draw.io (template-based).
 * Requirements: 28.1, 28.2, 1.1, 1.2
 */
@Serializable
data class DiagramData(
    val type: String = "",           // "flow", "component", "dependency", "deployment", "bpmn"
    val title: String = "",
    val mermaidCode: String = "",    // Mermaid syntax (when format = "mermaid")
    val format: String = "mermaid", // "mermaid" | "drawio" — default "mermaid" for backward compat (Req 1.1)
    val drawioMetadata: DrawioMetadata? = null  // nullable, only present when format = "drawio" (Req 1.2)
)
