package com.assistant.ai

import kotlinx.serialization.Serializable

/**
 * Sprint velocity data for a single sprint — used in Velocity Trend Chart.
 */
@Serializable
data class SprintVelocity(
    val sprintName: String,
    val storyPoints: Double
)

/**
 * Bottleneck alert generated by AI_Orchestrator analysis.
 * type: "RISK" or "OPTIMIZATION"
 * severity: "HIGH", "MEDIUM", "LOW"
 */
@Serializable
data class BottleneckAlert(
    val type: String,
    val severity: String,
    val title: String,
    val description: String
)

/**
 * Analysis status for long-polling progress tracking.
 * phase: "METADATA", "AI_ANALYZING", "KB_SYNCING", "COMPLETE"
 * progressPercent: 0-100
 */
@Serializable
data class AnalysisStatus(
    val ticketId: String,
    val phase: String,
    val progressPercent: Int
)

/**
 * Full project analysis response returned by GET /api/projects/{key}/analysis.
 */
@Serializable
data class ProjectAnalysisResponse(
    val projectKey: String,
    val totalTickets: Int,
    val resolutionRate: Double,
    val cycleTimeDays: Double,
    val aiVelocity: Double,
    val velocityTrend: List<SprintVelocity>,
    val bottlenecks: List<BottleneckAlert>,
    val providerStatuses: List<ProviderStatus>
)
