package com.assistant.ai

import kotlinx.serialization.Serializable

/**
 * Sprint velocity data for a single sprint — used in Velocity Trend Chart.
 */
@Serializable
data class SprintVelocity(
    val sprintName: String,
    val storyPoints: Double
)

/**
 * Bottleneck alert generated by AI_Orchestrator analysis.
 * type: "RISK" or "OPTIMIZATION"
 * severity: "HIGH", "MEDIUM", "LOW"
 */
@Serializable
data class BottleneckAlert(
    val type: String,
    val severity: String,
    val title: String,
    val description: String
)

/**
 * Analysis phases for deep analysis progress tracking (Req 21.4).
 * Each phase maps to a progress percentage range.
 */
enum class AnalysisPhase(val startPercent: Int, val endPercent: Int) {
    FETCHING_JIRA(0, 20),
    EXTRACTING_CONTENT(20, 35),
    AI_ANALYZING(35, 85),
    KB_SYNCING(85, 100),
    COMPLETE(100, 100);

    /** Legacy phase names for backward compatibility. */
    companion object {
        fun fromLegacy(phase: String): AnalysisPhase = when (phase) {
            "METADATA" -> FETCHING_JIRA
            else -> values().find { it.name == phase } ?: COMPLETE
        }
    }
}

/**
 * Analysis status for long-polling progress tracking (Req 21.4).
 * phase: FETCHING_JIRA, EXTRACTING_CONTENT, AI_ANALYZING, KB_SYNCING, COMPLETE
 * progressPercent: 0-100
 */
@Serializable
data class AnalysisStatus(
    val ticketId: String,
    val phase: String,
    val progressPercent: Int
)

/**
 * Full project analysis response returned by GET /api/projects/{key}/analysis.
 */
@Serializable
data class ProjectAnalysisResponse(
    val projectKey: String,
    val totalTickets: Int,
    val resolutionRate: Double,
    val cycleTimeDays: Double,
    val aiVelocity: Double,
    val velocityTrend: List<SprintVelocity>,
    val bottlenecks: List<BottleneckAlert>,
    val providerStatuses: List<ProviderStatus>
)
